# fly.toml app configuration file generated for ryanskinner-com on 2025-09-30T02:29:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ryanskinner-com'
primary_region = 'yyz'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2
memory_mb = 2048
