app = "ryanskinner-com"
primary_region = "yyz"

[build]

[env]
NODE_ENV = "production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = [ "app" ]

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/"

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2

[[statics]]
guest_path = "/app/.output/public"
url_prefix = "/_nuxt/"
