minimumReleaseAgeExclude:
  - rari-darwin-arm64@0.14.11
  - rari-darwin-x64@0.14.11
  - rari-linux-arm64@0.14.11
  - rari-linux-x64@0.14.11
  - rari-win32-arm64@0.14.11
  - rari-win32-x64@0.14.11
  - rari@0.14.11
shellEmulator: true
trustPolicy: no-downgrade
