minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - rari
  - rari-darwin-arm64
  - rari-darwin-x64
  - rari-linux-arm64
  - rari-linux-x64
  - rari-win32-arm64
  - rari-win32-x64
  - '@rari/lint'
  - '@voidzero-dev/vite-plus-core'
  - '@voidzero-dev/vite-plus-darwin-arm64'
  - '@voidzero-dev/vite-plus-darwin-x64'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu'
  - '@voidzero-dev/vite-plus-linux-arm64-musl'
  - '@voidzero-dev/vite-plus-linux-x64-gnu'
  - '@voidzero-dev/vite-plus-linux-x64-musl'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc'
  - '@voidzero-dev/vite-plus-win32-x64-msvc'
  - vite-plus

shellEmulator: true
trustPolicy: no-downgrade
